_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 256
epochs:
    value: 23
lr:
    value: 0.0001
temperature:
    value: 0.07
